export const countryCodeMap: Record<string, string> = {
    'antarctica': 'aq',
    'united states': 'us',
    'ireland': 'ie',
    'uganda': 'ug',
    'norway': 'no',
    'china': 'cn',
    'bolivia': 'bo',
    'mexico': 'mx',
    'singapore': 'sg',
    'timor leste': 'tl',
    'papua new guinea': 'pg',
    'rwanda': 'rw',
    'myanmar': 'mm',
    'el salvador': 'sv',
    'united kingdom': 'gb',
    'hawaii': 'us',
    'haiti': 'ht',
    'slovenia': 'si',
    'finland': 'fi',
    'italy': 'it',
    'colombia': 'co',
    'uae': 'ae',
    'denmark': 'dk',
    'czech republic': 'cz',
    'panama': 'pa',
    'kenya': 'ke',
    'india': 'in',
    'peru': 'pe',
    'malaysia': 'my',
    'costa rica': 'cr',
    'germany': 'de',
    'guatamala': 'gt', // typo
    'brazil': 'br',
    'spain': 'es',
    'ecuador': 'ec',
    'austria': 'at',
    'honduras': 'hn',
    'canada': 'ca',
    'ethiopia': 'et',
    'taiwan': 'tw',
    'democratic republic of the congo': 'cd',
    'nicaragua': 'ni',
    'indonesia': 'id',
    'laos': 'la',
    'australia': 'au',
    'vietnam': 'vn',
    'netherlands': 'nl',
    'switzerland': 'ch',
    'tanzania': 'tz',
    'belgium': 'be',
    'philippines': 'ph',
    'burundi': 'bi',
    'france': 'fr',
    'thailand': 'th',
    'dominican republic': 'do',
    'sweden': 'se',
    'jamaica': 'jm',
    'java': 'id',
    'malawi': 'mw',
    'yemen': 'ye',
    'south korea': 'kr',
    'south africa': 'za',
    'east timor': 'tl',
    'japan': 'jp',
    'ethiopa': 'et', // typo
    'usa': 'us',
    'nicarauga': 'ni', // typo
};
